### ISSUE TITLE
Recommended workflow for unit testing modules?

### ISSUE THREAD

**Issue by mokanfar** [michielgerritsen/magento2-extension-integration-test#18]
Hi, thanks for making this CI tool. I have yet to find a slimmer version. I want to use it for continuous testing and developing of a module.  Can you recommend a dev workflow against this docker container that you use for module integration testing?

Or is there a different docker container you use for module developing + testing?

**Comment by michielgerritsen** [comment]
Hi @mokanfar,

For the ongoing development, I would recommend using a local Magento 2 installation, optionally following the Composer route as described in this blogpost:
https://www.yireo.com/blog/2019-05-10-local-composer-development-with-magento2

From there you can develop everything, have your IDE autocomplete and you can run the unit and/or integration tests using the way Magento itself describes here:
https://devdocs.magento.com/guides/v2.4/test/integration/integration_test_execution.html

Hit me up if you got stuck in there somewhere ✌🏻
